version: "2.0"
services:
 vue-posts:
  build:
   context: .
   dockerfile: ./Dockerfile
  volumes:
  -   ./src:/usr/src/app/src
  -   ./public:/usr/src/app/public
  -   ./package.json:/usr/src/app/package.json
  -   .env:/usr/src/app/.env
  ports:
  -  "80:8080"
  -  "3000:3000"

